env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - 'standard'
  - 'eslint:recommended'
plugins:
  - standard
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
